export const FETCH_ALBUMS_PENDING = 'FETCH_ALBUMS_PENDING';
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';
export const FETCH_ALBUMS_REJECTED = 'FETCH_ALBUMS_REJECTED';

export const ADD_ALBUM = 'ADD_ALBUM';
export const REMOVE_ALBUM = 'REMOVE_ALBUM';
